obj-$(CONFIG_CHARGER_MAX77705)	+= max77705_charger.o
obj-$(CONFIG_SWITCHING_S2ASL01)	+= s2asl01_switching.o
obj-$(CONFIG_CHARGER_PCA9468)	+= pca9468_charger.o
obj-$(CONFIG_CHARGER_SM5705)	+= sm5705_charger.o sm5705_charger_oper.o
obj-$(CONFIG_CHARGER_SMB1351)   += smb1351_charger.o
obj-$(CONFIG_PM_S2MU107)  		+= s2mu107_pmeter.o
obj-$(CONFIG_CHARGER_S2MU107)   += s2mu107_switching_charger.o
obj-$(CONFIG_CHARGER_S2MU107_DIRECT)   += s2mu107_direct_charger.o