obj-$(CONFIG_SOC_EXYNOS8895) += gud-exynos8895/
#ifeq ($(CONFIG_GUD_DRIVER_Q_LAUNCHING), y)
#obj-$(CONFIG_SOC_EXYNOS9810) += gud-exynos9810_Q_Launching/
#else
obj-$(CONFIG_SOC_EXYNOS9810) += gud-exynos9810/
#endif
